"""Write the hash-pinned requirements of the Windows release builds (requirements/lock-cpu.txt, lock-gpu.txt).

Run after changing requirements/app.txt, build.txt or torch-*.txt (needs uv):  python tools/lock_requirements.py
The CI installs them with ``pip install --require-hashes``, so every build uses exactly the same packages.
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQ = ROOT / "requirements"
HEADER = ("# Generated by tools/lock_requirements.py from app.txt, build.txt and torch-{ed}.txt – do not edit.\n"
          "# Windows, Python 3.11; installed by the CI with: pip install --require-hashes -r lock-{ed}.txt\n")


def _lines(name: str) -> list[str]:
    return [ln for ln in (REQ / name).read_text(encoding="utf-8").splitlines() if ln.strip() and not ln.startswith("-")]


def main() -> int:
    common = _lines("app.txt") + _lines("build.txt")
    for ed in ("cpu", "gpu"):
        torch_txt = (REQ / f"torch-{ed}.txt").read_text(encoding="utf-8")
        index = re.search(r"--index-url\s+(\S+)", torch_txt).group(1)
        with tempfile.TemporaryDirectory() as tmp:
            src = Path(tmp) / "in.txt"
            src.write_text("\n".join(common + _lines(f"torch-{ed}.txt")) + "\n", encoding="utf-8")
            out = Path(tmp) / "lock.txt"
            subprocess.run(["uv", "pip", "compile", str(src), "--python-platform", "windows", "--python-version",
                            "3.11", "--generate-hashes", "--extra-index-url", index, "--index-strategy",
                            "unsafe-best-match", "--emit-index-url", "--no-header", "-o", str(out)], check=True)
            text = out.read_text(encoding="utf-8").replace(str(src), f"requirements (torch-{ed})")
        (REQ / f"lock-{ed}.txt").write_text(HEADER.format(ed=ed) + text, encoding="utf-8")
        print("wrote", REQ / f"lock-{ed}.txt")
    return 0


if __name__ == "__main__":
    sys.exit(main())
